# Application name
name: respond-app

# Environment variables
envVars: &envVars
  STAGE: ${opt:stage, self:provider.stage}

# Pipeline source directories
pipelines: &pipelines
  respond:
    - pipelines/respond
  respond-test:
    - pipelines/respond
    - pipelines/respond-test

# S3 bucket name
s3Bucket: &s3Bucket respond-app-${opt:stage, self:provider.stage}-bucket

# SSM key prefix
ssmKey: &ssmKey respond-app-${opt:stage, self:provider.stage}

# Environment-specific configuration
dev:
  envVars:
    <<: *envVars
  pipelines: *pipelines
  s3Bucket: *s3Bucket
  ssmKey: *ssmKey

stage:
  envVars:
    <<: *envVars
  pipelines: *pipelines
  s3Bucket: *s3Bucket
  ssmKey: *ssmKey

prod:
  envVars:
    <<: *envVars
  pipelines: *pipelines
  s3Bucket: *s3Bucket
  ssmKey: *ssmKey
