name: respond-app
bucket: &bucket respond-app-${opt:stage, self:provider.stage}-bucket
envVars: &envVars
  STAGE: ${opt:stage, self:provider.stage}
dev:
  bucket: *bucket
  envVars:
    <<: *envVars
stage:
  bucket: *bucket
  envVars:
    <<: *envVars
prod:
  bucket: *bucket
  envVars:
    <<: *envVars
