# Application name
name: app

# Environment variables
envVars: &envVars
  STAGE: ${opt:stage, self:provider.stage}

# Pipeline source directories
pipelines: &pipelines
  respond:
    - pipelines/respond
  respond-test:
    - pipelines/respond
    - pipelines/respond-test
  web-app:
    - pipelines/respond
    - pipelines/web-app

# S3 bucket name
s3Bucket: &s3Bucket app-${opt:stage, self:provider.stage}-bucket

# SSM key prefix
ssmKey: &ssmKey app-${opt:stage, self:provider.stage}

# Environment-specific configuration
dev:
  envVars:
    <<: *envVars
  pipelines: *pipelines
  s3Bucket: *s3Bucket
  ssmKey: *ssmKey

stage:
  envVars:
    <<: *envVars
  pipelines: *pipelines
  s3Bucket: *s3Bucket
  ssmKey: *ssmKey

prod:
  envVars:
    <<: *envVars
  pipelines: *pipelines
  s3Bucket: *s3Bucket
  ssmKey: *ssmKey
