service: ${file(./config/app.yml):name}

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${file(./config/app.yml):${opt:stage, self:provider.stage}.envVars}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:PutParameter
      Resource:
        - 'Fn::Join':
          - ':'
          - - 'arn:aws:ssm'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'parameter/${file(./config/app.yml):name}-${opt:stage, self:provider.stage}/*'
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - "arn:aws:s3:::${file(./config/app.yml):${opt:stage, self:provider.stage}.bucket}/*"
        - "arn:aws:s3:::${file(./config/app.yml):${opt:stage, self:provider.stage}.bucket}"

functions:
  postmaster:
    handler: dist-cjs/lib/respond/lambdaServer.lambdaServer
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
